name: Build and Upload .exe

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchamianie raz w tygodniu, w niedzielę o północy
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Run custom installation script
      run:  .installResources.bat
      shell: cmd

    - name: Build .exe
      run: .build.bat
      shell: cmd

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-executable
        path: path\to\your\output\executable.exe
